export const list = [
    {
      id: 1,
      name: "Black pepper chicken and Rice",
      price: 2500,
      img: "chinese 1.jpg",
      amount: 1,
      kind: "Chinese",
    },
    {
      id: 2,
      name: "Burger",
      price: 1200,
      img: "american 1.jpg",
      amount: 1,
      kind: "American",
    },
    {
      id: 3,
      name: "Jollof Rice and Fried Plantain",
      price: 1500,
      img: "african 1.jpg",
      amount: 1,
      kind: "African",
    },
    {
      id: 4,
      name: "Noodles",
      price: 2000,
      img: "chinese 2.jpg",
      amount: 1,
      kind: "Chinese",
    },
    {
      id: 5,
      name: "Hot dog",
      price: 1000,
      img: "american 2.jpg",
      amount: 1,
      kind: "American",
    },
    {
      id: 6,
      name: "White Rice and Vegetable Sauce with Plantain",
      price: 1700,
      img: "african 2.jpg",
      amount: 1,
      kind: "African",
    },
    {
      id: 7,
      name: "Fufu and Egusi Soup",
      price: 2000,
      img: "african 3.jpg",
      amount: 1,
      kind: "African",
    },
    {
      id: 8,
      name: "Hainanese chicken rice",
      price: 1800,
      img: "chinese 3.jpg",
      amount: 1,
      kind: "Chinese",
    },
    {
      id: 9,
      name: "Cobb salad",
      price: 1200,
      img: "american 3.jpg",
      amount: 1,
      kind: "American",
    },
    {
      id: 10,
      name: "Baked Apple Pie",
      price: 1500,
      img: "american 4.jpg",
      amount: 1,
      kind: "American",
    },
   ];